pipeline {
    agent any

    environment {
        VENV = '.venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'github-credentials', url: 'https://github.com/ziyadahmed-as/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    python3 -m venv ${VENV}
                    source ${VENV}/bin/activate
                    pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    source ${VENV}/bin/activate
                    pytest messaging_app/tests/ --junitxml=report.xml
                '''
            }
        }

        stage('Publish Report') {
            steps {
                junit 'report.xml'
            }
        }
    }

    triggers {
        // Manual trigger only
    }
}
