name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DJANGO_DB_NAME: test_db
      DJANGO_DB_USER: test_user
      DJANGO_DB_PASSWORD: test_pass
      DJANGO_DB_HOST: 127.0.0.1
      DJANGO_DB_PORT: 3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r messaging_app/requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL..."
          sleep 20

      - name: Run Django Tests
        run: |
          cd messaging_app
          python manage.py test
